lib/system/nuttx: fix undeclared parameter compile error
fix compile error:
/nuttx/openamp/libmetal/lib/system/nuttx/device.c:16:22: error:
'io' undeclared (first use in this function)
   16 |         metal_unused(io);
/nuttx/openamp/libmetal/lib/system/nuttx/device.c:14:53: error:
unused parameter 'dev' [-Werror=unused-parameter]
   14 | int metal_generic_dev_sys_open(struct metal_device *dev)
...

Signed-off-by: Yongrong Wang <wangyongrong@xiaomi.com>